name: build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "./src/Tailors.Web/package.json"
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Install dotnet dependencies
        run: dotnet restore
      - name: Install node dependencies
        run: npm ci
        working-directory: ./src/Tailors.Web
      - name: Build Tailwind
        run: npm run build:css
        working-directory: ./src/Tailors.Web
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
